CREATE TABLE IF NOT EXISTS `users` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`username` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `tasks` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`author_id` INT NOT NULL,
	`title` VARCHAR(255) NOT NULL,
	`description` VARCHAR(255) NOT NULL,
	`completed` TINYINT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY(`id`),
	FOREIGN KEY (`author_id`) REFERENCES `users`(`id`)
);